class Blueprint < ApplicationRecord
  extend FriendlyId

  belongs_to :user
  has_many :packages, dependent: :destroy
  has_many :dotfiles, dependent: :destroy
  has_many :environment_variables, dependent: :destroy
  has_many :services, dependent: :destroy

  friendly_id :name, use: :slugged

  validates :name, presence: true, length: { maximum: 120 }
  validates :slug, presence: true, uniqueness: { scope: :user_id }
  validates :description, length: { maximum: 500 }
  validates :yaml_content, presence: true

  scope :publicly, -> { where(public: true) }
  scope :recent, -> { order(created_at: :desc) }

  before_validation :generate_yaml_content, on: :create, if: -> { yaml_content.blank? }
  before_validation :generate_slug, on: :create, if: -> { slug.blank? }

  def to_param
    slug
  end

  def share_url(request_base)
    "#{request_base}/@#{user.to_slug}/#{slug}"
  end

  def to_shell_script
    script = ["#!/usr/bin/env bash", "set -euo pipefail", ""]
    script << "# Blueprint: #{name}"
    script << "# Generated by blueprint.dev"
    script << ""

    if packages.any?
      script << "# Packages"
      packages.group_by(&:category).each do |category, pkgs|
        script << "# #{category.titleize}" if category.present?
        pkgs.each { |p| script << package_install_command(p) }
      end
      script << ""
    end

    if environment_variables.any?
      script << "# Environment Variables"
      environment_variables.each do |ev|
        script << %(echo 'export #{ev.key}="#{ev.value}"' >> ~/.bashrc)
      end
      script << ""
    end

    if dotfiles.any?
      script << "# Dotfiles"
      dotfiles.each do |df|
        script << "mkdir -p $(dirname #{Shellwords.escape(df.target_path)})"
        script << %(cat > #{Shellwords.escape(df.target_path)} << 'DOTFILE_EOF')
        script << df.content
        script << "DOTFILE_EOF"
      end
      script << ""
    end

    if services.any?
      script << "# Services"
      services.each do |svc|
        action = svc.enabled ? "enable --now" : "disable --now"
        script << "sudo systemctl #{action} #{svc.name}"
      end
    end

    script.join("\n") + "\n"
  end

  private

  def package_install_command(pkg)
    case pkg.category
    when "aur"
      "paru -S --noconfirm #{pkg.name}"
    when "pip"
      "pip install #{pkg.name}"
    when "npm"
      "npm install -g #{pkg.name}"
    else
      "sudo pacman -S --noconfirm #{pkg.name}"
    end
  end

  def generate_slug
    self.slug = name.to_s.downcase.gsub(/[^a-z0-9]+/, "-").gsub(/^-|-$/, "")
  end

  def generate_yaml_content
    self.yaml_content = <<~YAML
      name: "#{name}"
      description: "#{description}"
      packages: []
      dotfiles: []
      environment: {}
      services: []
    YAML
  end
end
